// IMPLEMENTATION-ONLY PIN/CLOCK PROOF. Never program this test onto hardware.
// Test output signatures are not valid ASIC SPI/reset/stimulation signals.
// No .bit file is generated by run_clock_proof.tcl.
`timescale 1ns/1ps
module clock_pin_proof(
    input wire ASIC1_DATA1,
    input wire ASIC1_DATA2,
    input wire ASIC1_DATA3,
    input wire ASIC1_DATA4,
    input wire ASIC1_DATA5,
    input wire ASIC1_DATA6,
    input wire ASIC1_DATA7,
    input wire ASIC1_DATA8,
    input wire ASIC1_CLK32MHz_Out,
    input wire ASIC1_READ,
    input wire ASIC1_SYNC,
    input wire ASIC2_DATA1,
    input wire ASIC2_DATA2,
    input wire ASIC2_DATA3,
    input wire ASIC2_DATA4,
    input wire ASIC2_DATA5,
    input wire ASIC2_DATA6,
    input wire ASIC2_DATA7,
    input wire ASIC2_DATA8,
    input wire ASIC2_CLK32MHz_Out,
    input wire ASIC2_READ,
    input wire ASIC2_SYNC,
    input wire ASIC3_DATA1,
    input wire ASIC3_DATA2,
    input wire ASIC3_DATA3,
    input wire ASIC3_DATA4,
    input wire ASIC3_DATA5,
    input wire ASIC3_DATA6,
    input wire ASIC3_DATA7,
    input wire ASIC3_DATA8,
    input wire ASIC3_CLK32MHz_Out,
    input wire ASIC3_READ,
    input wire ASIC3_SYNC,
    input wire ASIC4_DATA1,
    input wire ASIC4_DATA2,
    input wire ASIC4_DATA3,
    input wire ASIC4_DATA4,
    input wire ASIC4_DATA5,
    input wire ASIC4_DATA6,
    input wire ASIC4_DATA7,
    input wire ASIC4_DATA8,
    input wire ASIC4_CLK32MHz_Out,
    input wire ASIC4_READ,
    input wire ASIC4_SYNC,
    input wire ASIC5_DATA1,
    input wire ASIC5_DATA2,
    input wire ASIC5_DATA3,
    input wire ASIC5_DATA4,
    input wire ASIC5_DATA5,
    input wire ASIC5_DATA6,
    input wire ASIC5_DATA7,
    input wire ASIC5_DATA8,
    input wire ASIC5_CLK32MHz_Out,
    input wire ASIC5_READ,
    input wire ASIC5_SYNC,
    input wire ASIC6_DATA1,
    input wire ASIC6_DATA2,
    input wire ASIC6_DATA3,
    input wire ASIC6_DATA4,
    input wire ASIC6_DATA5,
    input wire ASIC6_DATA6,
    input wire ASIC6_DATA7,
    input wire ASIC6_DATA8,
    input wire ASIC6_CLK32MHz_Out,
    input wire ASIC6_READ,
    input wire ASIC6_SYNC,
    input wire ASIC7_DATA1,
    input wire ASIC7_DATA2,
    input wire ASIC7_DATA3,
    input wire ASIC7_DATA4,
    input wire ASIC7_DATA5,
    input wire ASIC7_DATA6,
    input wire ASIC7_DATA7,
    input wire ASIC7_DATA8,
    input wire ASIC7_CLK32MHz_Out,
    input wire ASIC7_READ,
    input wire ASIC7_SYNC,
    input wire ASIC8_DATA1,
    input wire ASIC8_DATA2,
    input wire ASIC8_DATA3,
    input wire ASIC8_DATA4,
    input wire ASIC8_DATA5,
    input wire ASIC8_DATA6,
    input wire ASIC8_DATA7,
    input wire ASIC8_DATA8,
    input wire ASIC8_CLK32MHz_Out,
    input wire ASIC8_READ,
    input wire ASIC8_SYNC,
    output wire CHIP_RESET_SHARED,
    output wire IMP_TST_SHARED,
    output wire FE_RESET_SHARED,
    output wire SPI_LATCH_SHARED,
    output wire STIM_CLK_SHARED,
    output wire STIM_START_SHARED,
    output wire STIM_EN_SHARED,
    output wire STIM_CHB_SHARED,
    output wire BOARD1_CLK,
    output wire BOARD2_CLK,
    output wire BOARD3_CLK,
    output wire BOARD4_CLK,
    output wire STIM_CHIP1_SPI_DL,
    output wire STIM_CHIP1_SPI_DR,
    output wire STIM_CHIP2_SPI_DL,
    output wire STIM_CHIP2_SPI_DR,
    output wire STIM_CHIP3_SPI_DL,
    output wire STIM_CHIP3_SPI_DR,
    output wire STIM_CHIP4_SPI_DL,
    output wire STIM_CHIP4_SPI_DR,
    output wire NONSTIM_BOARD1_SPI_DL,
    output wire NONSTIM_BOARD1_SPI_DR,
    output wire NONSTIM_BOARD2_SPI_DL,
    output wire NONSTIM_BOARD2_SPI_DR,
    output wire BOARD1_SPI_CLK,
    output wire BOARD2_SPI_CLK,
    output wire BOARD3_SPI_CLK,
    output wire BOARD4_SPI_CLK
);
    wire clk1_ibuf, clk1_global;
    IBUF clock1_input(.I(ASIC1_CLK32MHz_Out), .O(clk1_ibuf));
    (* DONT_TOUCH = "TRUE" *) BUFG clock1_global(.I(clk1_ibuf), .O(clk1_global));
    (* DONT_TOUCH = "TRUE", IOB = "TRUE" *) reg [9:0] sample1;
    always @(negedge clk1_global) sample1 <= {ASIC1_DATA1, ASIC1_DATA2, ASIC1_DATA3, ASIC1_DATA4, ASIC1_DATA5, ASIC1_DATA6, ASIC1_DATA7, ASIC1_DATA8, ASIC1_READ, ASIC1_SYNC};
    wire clk2_ibuf, clk2_global;
    IBUF clock2_input(.I(ASIC2_CLK32MHz_Out), .O(clk2_ibuf));
    (* DONT_TOUCH = "TRUE" *) BUFG clock2_global(.I(clk2_ibuf), .O(clk2_global));
    (* DONT_TOUCH = "TRUE", IOB = "TRUE" *) reg [9:0] sample2;
    always @(negedge clk2_global) sample2 <= {ASIC2_DATA1, ASIC2_DATA2, ASIC2_DATA3, ASIC2_DATA4, ASIC2_DATA5, ASIC2_DATA6, ASIC2_DATA7, ASIC2_DATA8, ASIC2_READ, ASIC2_SYNC};
    wire clk3_ibuf, clk3_global;
    IBUF clock3_input(.I(ASIC3_CLK32MHz_Out), .O(clk3_ibuf));
    (* DONT_TOUCH = "TRUE" *) BUFG clock3_global(.I(clk3_ibuf), .O(clk3_global));
    (* DONT_TOUCH = "TRUE", IOB = "TRUE" *) reg [9:0] sample3;
    always @(negedge clk3_global) sample3 <= {ASIC3_DATA1, ASIC3_DATA2, ASIC3_DATA3, ASIC3_DATA4, ASIC3_DATA5, ASIC3_DATA6, ASIC3_DATA7, ASIC3_DATA8, ASIC3_READ, ASIC3_SYNC};
    wire clk4_ibuf, clk4_global;
    IBUF clock4_input(.I(ASIC4_CLK32MHz_Out), .O(clk4_ibuf));
    (* DONT_TOUCH = "TRUE" *) BUFG clock4_global(.I(clk4_ibuf), .O(clk4_global));
    (* DONT_TOUCH = "TRUE", IOB = "TRUE" *) reg [9:0] sample4;
    always @(negedge clk4_global) sample4 <= {ASIC4_DATA1, ASIC4_DATA2, ASIC4_DATA3, ASIC4_DATA4, ASIC4_DATA5, ASIC4_DATA6, ASIC4_DATA7, ASIC4_DATA8, ASIC4_READ, ASIC4_SYNC};
    wire clk5_ibuf, clk5_global;
    IBUF clock5_input(.I(ASIC5_CLK32MHz_Out), .O(clk5_ibuf));
    (* DONT_TOUCH = "TRUE" *) BUFG clock5_global(.I(clk5_ibuf), .O(clk5_global));
    (* DONT_TOUCH = "TRUE", IOB = "TRUE" *) reg [9:0] sample5;
    always @(negedge clk5_global) sample5 <= {ASIC5_DATA1, ASIC5_DATA2, ASIC5_DATA3, ASIC5_DATA4, ASIC5_DATA5, ASIC5_DATA6, ASIC5_DATA7, ASIC5_DATA8, ASIC5_READ, ASIC5_SYNC};
    wire clk6_ibuf, clk6_global;
    IBUF clock6_input(.I(ASIC6_CLK32MHz_Out), .O(clk6_ibuf));
    (* DONT_TOUCH = "TRUE" *) BUFG clock6_global(.I(clk6_ibuf), .O(clk6_global));
    (* DONT_TOUCH = "TRUE", IOB = "TRUE" *) reg [9:0] sample6;
    always @(negedge clk6_global) sample6 <= {ASIC6_DATA1, ASIC6_DATA2, ASIC6_DATA3, ASIC6_DATA4, ASIC6_DATA5, ASIC6_DATA6, ASIC6_DATA7, ASIC6_DATA8, ASIC6_READ, ASIC6_SYNC};
    wire clk7_ibuf, clk7_global;
    IBUF clock7_input(.I(ASIC7_CLK32MHz_Out), .O(clk7_ibuf));
    (* DONT_TOUCH = "TRUE" *) BUFG clock7_global(.I(clk7_ibuf), .O(clk7_global));
    (* DONT_TOUCH = "TRUE", IOB = "TRUE" *) reg [9:0] sample7;
    always @(negedge clk7_global) sample7 <= {ASIC7_DATA1, ASIC7_DATA2, ASIC7_DATA3, ASIC7_DATA4, ASIC7_DATA5, ASIC7_DATA6, ASIC7_DATA7, ASIC7_DATA8, ASIC7_READ, ASIC7_SYNC};
    wire clk8_ibuf, clk8_global;
    IBUF clock8_input(.I(ASIC8_CLK32MHz_Out), .O(clk8_ibuf));
    (* DONT_TOUCH = "TRUE" *) BUFG clock8_global(.I(clk8_ibuf), .O(clk8_global));
    (* DONT_TOUCH = "TRUE", IOB = "TRUE" *) reg [9:0] sample8;
    always @(negedge clk8_global) sample8 <= {ASIC8_DATA1, ASIC8_DATA2, ASIC8_DATA3, ASIC8_DATA4, ASIC8_DATA5, ASIC8_DATA6, ASIC8_DATA7, ASIC8_DATA8, ASIC8_READ, ASIC8_SYNC};
    assign CHIP_RESET_SHARED = ^sample1;
    assign IMP_TST_SHARED = ^sample2;
    assign FE_RESET_SHARED = ^sample3;
    assign SPI_LATCH_SHARED = ^sample4;
    assign STIM_CLK_SHARED = ^sample5;
    assign STIM_START_SHARED = ^sample6;
    assign STIM_EN_SHARED = ^sample7;
    assign STIM_CHB_SHARED = ^sample8;
    assign BOARD1_CLK = ^sample1;
    assign BOARD2_CLK = ^sample2;
    assign BOARD3_CLK = ^sample3;
    assign BOARD4_CLK = ^sample4;
    assign STIM_CHIP1_SPI_DL = ^sample5;
    assign STIM_CHIP1_SPI_DR = ^sample6;
    assign STIM_CHIP2_SPI_DL = ^sample7;
    assign STIM_CHIP2_SPI_DR = ^sample8;
    assign STIM_CHIP3_SPI_DL = ^sample1;
    assign STIM_CHIP3_SPI_DR = ^sample2;
    assign STIM_CHIP4_SPI_DL = ^sample3;
    assign STIM_CHIP4_SPI_DR = ^sample4;
    assign NONSTIM_BOARD1_SPI_DL = ^sample5;
    assign NONSTIM_BOARD1_SPI_DR = ^sample6;
    assign NONSTIM_BOARD2_SPI_DL = ^sample7;
    assign NONSTIM_BOARD2_SPI_DR = ^sample8;
    assign BOARD1_SPI_CLK = ^sample1;
    assign BOARD2_SPI_CLK = ^sample2;
    assign BOARD3_SPI_CLK = ^sample3;
    assign BOARD4_SPI_CLK = ^sample4;
endmodule
