/* Presentation copy. Reported assignments are not GitHub layout reservations.
 * Repository sources are dated; reference-board dimensions are not new design targets.
 */
(() => {
  const repo = 'https://github.com/HowardWHSrun/FPGA_4K/blob/presentation/';
  const refs = {
    team: ['Team assignments · received Sep 18', repo+'docs/meetings/2026-09-18-follow-up.md'],
    hardware: ['Supplied board references', repo+'hardware/overview.md'],
    fpga: ['FPGA working draft · Sep 21 import', repo+'hardware/fpga-board/README.md'],
    open: ['Owners and open requirements', repo+'docs/team/owners-and-work.md'],
    meeting: ['System and interface discussion · Sep 17', repo+'docs/meetings/2026-09-17.md'],
    amd: ['AMD · KR260 platform specification', 'https://www.amd.com/en/products/system-on-modules/kria/k26/kr260-robotics-starter-kit.html']
  };
  window.PRESENTATION_SLIDES = [
    {id:'overview',section:'System overview',title:'4K neural recording',subtitle:'Headboard to host.',description:'Select a board to explore its function, owner and current design questions.',regions:['A','C','D','E'],owners:[],facts:[['4','carrier boards'],['8','ASICs in the concept'],['4,096','target channels']],noteLabel:'Shared design focus',note:'Agree on the interfaces between boards: signals, power, configuration and the downstream data link.',details:['The compact B v1 headboard is shown without changing its source geometry. The former bridge is grouped with the routing/LDO board, following Howard’s September 22 instruction.','KR260 is an added downstream system layer. Its schematic representation is not part of the supplied STL and does not imply a physical headstage stack or relative scale.','Names are the reported workstream assignments in the September 18 follow-up. GitHub layout reservations and reviewer usernames remain TBD in the separate ownership register.'],sources:[refs.team,refs.hardware,refs.open]},
    {id:'carriers',section:'01 · Recording front end',title:'ASIC carrier stack',subtitle:'Gerald · ASIC and carrier design',description:'Four two-chip carriers form the recording front end. Each carrier is discussed as a 1,024-channel board.',regions:['A'],owners:[['Gerald','ASIC / carrier PCB']],facts:[['2','ASICs per carrier'],['1,024','channels per carrier'],['4','stacked carriers']],noteLabel:'Interface to resolve',note:'Gerald supplies the authoritative chip pin map; align the carrier connections with Zitong and Howard.',details:['The reported assignment includes the ASIC and 1,024-channel two-chip carrier designs. This is ownership and architecture, not a claim of completed 4K operation.','PCB-5 is the supplied reference: approximately 22 × 17 mm, 10 copper layers, two chip footprints and an 80-contact J3 connector. These are reference-board facts, not dimensions for the compact STL.','The team follow-up records a nominal 1.5 V reference and an intended 32 MHz ASIC clock. Complete supply rails, I/O limits and timing requirements remain to be specified.'],sources:[refs.team,refs.hardware,refs.meeting]},
    {id:'routing',section:'02 · Routing and power',title:'Routing + LDO board',subtitle:'Zitong · Routing and power PCB',description:'One workstream carries the chip signals and handles the routing/power board. The short connecting section is part of this board—not a separate bridge subsystem.',regions:['C'],owners:[['Zitong','Routing / power management']],facts:[['B + C','one routing/LDO region'],['Signals','carrier → FPGA'],['Power','regulation / distribution']],noteLabel:'Interface to resolve',note:'Reconcile connector pin maps, grounds and I/O levels. Confirm rail requirements and regulator placement with the adjacent boards.',details:['The former bridge and lower board share one label, selection and color. Geometry is preserved; no separate bridge part is introduced.','The historical LDO/routing reference is approximately 18.3 × 42 mm with 6 copper layers and nine regulator footprints. It is an example to adapt, not the finished eight-chip power design.','That reference has 50-contact board-to-board connectors, while PCB-5 has an 80-contact connector. The references are not a verified mating pair.','The September 17 meeting places FPGA power circuitry on the FPGA board; recording-chip regulator placement is still under review.'],sources:[refs.team,refs.hardware,refs.meeting,refs.open]},
    {id:'fpga',section:'03 · Acquisition and aggregation',title:'FPGA hardware + logic',subtitle:'Howard · PCB     /     Jiaao · Firmware',description:'Receive and organize the chip data, provide the acquisition logic, and forward the stream to the downstream platform.',regions:['D'],owners:[['Howard','FPGA PCB'],['Jiaao','FPGA programming']],facts:[['XC7A200T','documented device direction'],['42 × 40 mm','Sep 21 PCB draft'],['Bring-up','power / configuration / link']],noteLabel:'Current recorded status',note:'The imported PCB is a partial design, not a fabrication release. Link protocol, clocking, power and application pin assignments remain open.',details:['The September 21 handoff includes a 41-sheet KiCad hierarchy and a partial 42 × 40 mm FPGA board. Device direction is XC7A200T; the full package/speed/temperature ordering code still needs qualification.','At import, the 22-net programming scope was routed. Reports list 270 remaining PCB connection items, 661 unresolved schematic pins and 21 undriven power pins. These are dated import results, not live counts.','The bundled FPGA_512 firmware is an earlier ECP5/FT600 implementation. It does not establish Artix-7 compatibility or demonstrated full-4K performance.','The proposed development sequence starts with evaluation-board/FX3 testing and FPGA-generated data, then moves to the custom board and complete system. The repository does not record these as passed tests.'],sources:[refs.team,refs.fpga,refs.open]},
    {id:'kr260',section:'04 · Downstream control and streaming',title:'KR260 control layer',subtitle:'David · Downstream / “MCU” programming',description:'The downstream platform receives the FPGA stream, provides the intended control path, and forwards data toward the PC.',regions:['E'],owners:[['David','Downstream / “MCU” software']],facts:[['KR260','selected downstream platform'],['K26 SOM','Zynq UltraScale+ MPSoC'],['SFP+ → PC','intended forwarding path']],noteLabel:'Interface to resolve',note:'David and Jiaao coordinate with the PCB designers on reception, control and forwarding. The FPGA-to-KR260 electrical link is not finalized.',details:['“MCU” is the team’s workstream name. Technically, KR260 is a K26 SOM / Zynq UltraScale+ MPSoC development platform, not a standalone microcontroller chip. This hardware clarification is from AMD, separate from the repository’s project decisions.','AMD lists 4 GB DDR4 and a 10G-capable SFP+ interface. These are platform capabilities, not achieved rates for this recording system.','The team records ASIC boards → routing → FPGA → cable → downstream platform → SFP+ → PC. Connector format alone does not establish USB, HDMI or direct receiver compatibility.','The added KR260 visual is a schematic system-stage illustration, not manufacturer CAD. No relative scale, mating footprint or physical stack arrangement is asserted.'],sources:[refs.team,refs.meeting,refs.amd,refs.open]}
  ];
})();
